<a href="https://colab.research.google.com/github/devrahul9119/python_practice/blob/master/data_toll_free_nov_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [ ]:
sc_payment1 = pd.read_excel('service_center_nov_payment.xlsx',sheet_name = '1to5Nov')
sc_payment2 = pd.read_excel('service_center_nov_payment.xlsx',sheet_name = '6to10Nov')
sc_payment3 = pd.read_excel('service_center_nov_payment.xlsx',sheet_name = '11to29Nov')
sc_payment4 = pd.read_excel('service_center_nov_payment.xlsx',sheet_name = '30Nov23')

In [ ]:
sc_payment1['Distances'] = sc_payment1['Distances'].round()
sc_payment2['Distances'] = sc_payment2['Distances'].round()
sc_payment3['Distances'] = sc_payment3['Distances'].round()
sc_payment4['Distances'] = sc_payment4['Distances'].round()

In [ ]:
sc_payments = pd.concat([sc_payment1,sc_payment2,sc_payment3,sc_payment4],axis = 0,ignore_index = True)
sc_payments

,Service Center Name,COMPLAINT CLOSE DATE,COMPLAINT SEND & REC. DATE,COMPLAINT NO,NAME,ADDRESS,DISTRICT,Distances,TREVELLING FROM,REMARK,LOCATION/2 PCS/2 VISIT
0,AMIT PATHAK FIROZPUR,02.11.23,30.10.23,RAPLWHK1660,PRITPAL SINGH,VILL UKANDWALA TEH JAITO,FARIDKOT,63.0,AZAD NAGAR 152002,NaN,NaN
1,AMIT PATHAK FIROZPUR,01.11.23,30.10.23,RAPLWHK1692,GURBINDER SINGH,BHEAK GUJJRAN ZIRA,FIROZPUR,47.0,AZAD NAGAR 152002,NaN,NaN
2,AMIT PATHAK FIROZPUR,01.11.23,30.10.23,RAPLWHK1717,SEEMA,BASTI AAWA,FIROZPUR,9.0,AZAD NAGAR 152002,NaN,2 VISIT
3,AMIT PATHAK FIROZPUR,02.11.23,30.10.23,RAPLWHK1742,STAPAL,GONDARA,FARIDKOT,73.0,AZAD NAGAR 152002,NaN,NaN
4,AMIT PATHAK FIROZPUR,01.11.23,31.10.23,RAPLWHK1768,KALA SINGH,KALU WALA,FIROZPUR,16.0,AZAD NAGAR 152002,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1634,VISHAL YAMUNAGAR,NaN,27.11.23,RAPLWHL1686,JASHN JEET,RAMGARH MAJRA 135102,YAMUNANAGAR,21.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL DONE,NaN
1635,VISHAL YAMUNAGAR,NaN,27.11.23,RAPLWHL1701,SALMAN,BIBIPUR,YAMUNANAGAR,14.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL DONE,NaN
1636,VISHAL YAMUNAGAR,NaN,28.11.23,RAPLWHL1715,SANJEEV,143 SEC 17 HUDA NEAR RADHA KRISHAN MANDIR YAMU...,YAMUNANAGAR,3.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL DONE,NaN
1637,VISHAL YAMUNAGAR,NaN,28.11.23,RAPLWHL1746,GAURAV,SUDHAIL SASOLI,YAMUNANAGAR,10.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL DONE,NaN
1638,VISHAL YAMUNAGAR,NaN,30.11.23,RAPLWHL1927,BALKAR SINGH,ARIYAWALA YAMUNANAGAR 133204,YAMUNANAGAR,21.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL NOT PIC,NaN

In [ ]:
sc_payment_1.to_excel('final_data_nov.xlsx')

In [ ]:
sc_payment_1 = sc_payments.merge(sc_address,how ='left',left_on ='TREVELLING FROM',right_on = 'TREVELING FROM')

In [ ]:
sc_payment_1

,Service Center Name_x,COMPLAINT CLOSE DATE,COMPLAINT SEND & REC. DATE,COMPLAINT NO,NAME,ADDRESS,DISTRICT,Distances,TREVELLING FROM,REMARK,LOCATION/2 PCS/2 VISIT,Service Center Name_y,TREVELING FROM,PER COMPLAINT,KILOMETER UPDOWN,PER KM
0,AMIT PATHAK FIROZPUR,02.11.23,30.10.23,RAPLWHK1660,PRITPAL SINGH,VILL UKANDWALA TEH JAITO,FARIDKOT,63.0,AZAD NAGAR 152002,NaN,NaN,AMIT PATHAK FIROZPUR,AZAD NAGAR 152002,250,50.0,4.0
1,AMIT PATHAK FIROZPUR,01.11.23,30.10.23,RAPLWHK1692,GURBINDER SINGH,BHEAK GUJJRAN ZIRA,FIROZPUR,47.0,AZAD NAGAR 152002,NaN,NaN,AMIT PATHAK FIROZPUR,AZAD NAGAR 152002,250,50.0,4.0
2,AMIT PATHAK FIROZPUR,01.11.23,30.10.23,RAPLWHK1717,SEEMA,BASTI AAWA,FIROZPUR,9.0,AZAD NAGAR 152002,NaN,2 VISIT,AMIT PATHAK FIROZPUR,AZAD NAGAR 152002,250,50.0,4.0
3,AMIT PATHAK FIROZPUR,02.11.23,30.10.23,RAPLWHK1742,STAPAL,GONDARA,FARIDKOT,73.0,AZAD NAGAR 152002,NaN,NaN,AMIT PATHAK FIROZPUR,AZAD NAGAR 152002,250,50.0,4.0
4,AMIT PATHAK FIROZPUR,01.11.23,31.10.23,RAPLWHK1768,KALA SINGH,KALU WALA,FIROZPUR,16.0,AZAD NAGAR 152002,NaN,NaN,AMIT PATHAK FIROZPUR,AZAD NAGAR 152002,250,50.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1634,VISHAL YAMUNAGAR,NaN,27.11.23,RAPLWHL1686,JASHN JEET,RAMGARH MAJRA 135102,YAMUNANAGAR,21.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL DONE,NaN,VISHAL YAMUNANAGAR,gulab nagar jagadhari pabni raod jagadhri yamu...,300,40.0,4.0
1635,VISHAL YAMUNAGAR,NaN,27.11.23,RAPLWHL1701,SALMAN,BIBIPUR,YAMUNANAGAR,14.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL DONE,NaN,VISHAL YAMUNANAGAR,gulab nagar jagadhari pabni raod jagadhri yamu...,300,40.0,4.0
1636,VISHAL YAMUNAGAR,NaN,28.11.23,RAPLWHL1715,SANJEEV,143 SEC 17 HUDA NEAR RADHA KRISHAN MANDIR YAMU...,YAMUNANAGAR,3.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL DONE,NaN,VISHAL YAMUNANAGAR,gulab nagar jagadhari pabni raod jagadhri yamu...,300,40.0,4.0
1637,VISHAL YAMUNAGAR,NaN,28.11.23,RAPLWHL1746,GAURAV,SUDHAIL SASOLI,YAMUNANAGAR,10.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL DONE,NaN,VISHAL YAMUNANAGAR,gulab nagar jagadhari pabni raod jagadhri yamu...,300,40.0,4.0
1638,VISHAL YAMUNAGAR,NaN,30.11.23,RAPLWHL1927,BALKAR SINGH,ARIYAWALA YAMUNANAGAR 133204,YAMUNANAGAR,21.0,gulab nagar jagadhari pabni raod jagadhri yamu...,CALL NOT PIC,NaN,VISHAL YAMUNANAGAR,gulab nagar jagadhari pabni raod jagadhri yamu...,300,40.0,4.0

In [ ]:
df = pd.read_excel('final_data_nov.xlsx')

In [ ]:
df['Distances']

0       63.0
1       47.0
2        9.0
3       73.0
4       16.0
        ...
1634    21.0
1635    14.0
1636     3.0
1637    10.0
1638    21.0
Name: Distances, Length: 1639, dtype: float64

In [ ]:
df['up_down_dist'] = df['Distances']*2

In [ ]:
df['up_down_dist']

0       126.0
1        94.0
2        18.0
3       146.0
4        32.0
        ...
1634     42.0
1635     28.0
1636      6.0
1637     20.0
1638     42.0
Name: up_down_dist, Length: 1639, dtype: float64

In [ ]:
df['difference'] = (df['up_down_dist'] - df['KILOMETER UPDOWN']).clip(lower=0)

In [ ]:
df['difference']

0       76.0
1       44.0
2        0.0
3       96.0
4        0.0
        ...
1634     2.0
1635     0.0
1636     0.0
1637     0.0
1638     2.0
Name: difference, Length: 1639, dtype: float64

In [ ]:
df['PER COMPLAINT'] = df['PER COMPLAINT'].fillna(0)

In [ ]:
df.loc[df['PER COMPLAINT'] == '250/ outer 275', 'PER COMPLAINT'] = 250

In [ ]:
df['PER COMPLAINT'] = df['PER COMPLAINT'].astype('float64')

In [ ]:
df['total_amount'] = df['PER COMPLAINT']+df['difference']*df['PER KM']

In [ ]:
df['total_amount']

0       554.0
1       426.0
2       250.0
3       634.0
4       250.0
        ...
1634    308.0
1635    300.0
1636    300.0
1637    300.0
1638    308.0
Name: total_amount, Length: 1639, dtype: float64

In [ ]:
new_df = df.groupby(['Service Center Name_x'])['total_amount'].sum()

In [ ]:
new_df = pd.DataFrame(new_df)

In [ ]:
new_df['total_amount'].sum()

544992.0

In [ ]:
df.to_excel('final_nov_payment.xlsx')

In [2]:
new_df = pd.read_excel('final_nov_payment.xlsx')

In [7]:
new_df.groupby(['Service Center Name_x'])['total_amount'].sum().sort_values(ascending = False).head()

Service Center Name_x
AMIT PATHAK FIROZPUR    52160.0
JITENDER BATHINDA       44902.0
VIJAY KATHUA            41468.0
DALIP ABOHAR            40922.0
KRISHAN PATIALA         34460.0
Name: total_amount, dtype: float64

In [ ]:
new_df['total_amount'].sort_values()

Service Center Name_x
RAJINDER GANGANAGAR           0.0
TOSIM MOHAMD MORADABAD        0.0
RENU MAM                      0.0
JASVIR HARIDWAR             250.0
LALT UNA                    250.0
                           ...
KRISHAN PATIALA           34460.0
DALIP ABOHAR              40922.0
VIJAY KATHUA              41468.0
JITENDER BATHINDA         44902.0
AMIT PATHAK FIROZPUR      52160.0
Name: total_amount, Length: 74, dtype: float64

In [ ]:
df[df['REMARK'].isin([2,3,1])]

,Service Center Name_x,COMPLAINT CLOSE DATE,COMPLAINT SEND & REC. DATE,COMPLAINT NO,NAME,ADDRESS,DISTRICT,Distances,TREVELLING FROM,REMARK,LOCATION/2 PCS/2 VISIT,PER COMPLAINT,KILOMETER UPDOWN,PER KM,up_down_dist,difference,total_amount
74,AMIT PATHAK FIROZPUR,NaN,15.11.23,RAPLWHL745,ABHI,TUMBER BHAN 142050,FIROZPUR,34.0,AZAD NAGAR 152002,2.0,NaN,250.0,50.0,4.0,68.0,18.0,322.0
219,ARVID ZIRAKPUR,NaN,17.11.23,RAPLWHL912,PARTIBHA,SBP HOUSING PARK 216 MOKSHA TOWER 140507 \nDER...,MOHALI,8.0,dhakoli 140603,2.0,NaN,250.0,50.0,4.0,16.0,0.0,250.0
227,ARVIND ZIRAKPUR,NaN,22.11.23,RAPLWHL1340,RAKESH KUMAR SHARMA,VILL JAROUT 140501,MOHALI,32.0,dhakoli 140603,2.0,NaN,250.0,50.0,4.0,64.0,14.0,306.0
231,ARVIND ZIRAKPUR,NaN,24.11.23,RAPLWHL1490,BHAGAT SALER,BHAGAT SALER AMBALA CHD EXPY LALRU 140501,MOHALI,22.0,dhakoli 140603,2.0,NaN,250.0,50.0,4.0,44.0,0.0,250.0
389,DALIP ABOHAR,NaN,09.11.23,RAPLWHL474,JATIN,MALOUT 152107,MUKATSAR SAHIB,36.0,"Street Number 15, Nai Abadi, Abohar, Punjab 15...",2.0,NaN,250.0,50.0,4.0,72.0,22.0,338.0
390,DALIP ABOHAR,NaN,09.11.23,RAPLWHL505,SUMEDH,MIDDA 151210,MUKATSAR SAHIB,29.0,"Street Number 15, Nai Abadi, Abohar, Punjab 15...",2.0,NaN,250.0,50.0,4.0,58.0,8.0,282.0
405,DALIP ABOHAR,NaN,14.11.23,RAPLWHL703,NIRAML SINGH,KAUNI 152031,MUKATSAR SAHIB,65.0,"Street Number 15, Nai Abadi, Abohar, Punjab 15...",2.0,NaN,250.0,50.0,4.0,130.0,80.0,570.0
409,DALIP ABOHAR,NaN,15.11.23,RAPLWHL752,GURPREET SINGH,KOTBAHI GIDERBAHA 152026,MUKATSAR SAHIB,56.0,"Street Number 15, Nai Abadi, Abohar, Punjab 15...",2.0,NaN,250.0,50.0,4.0,112.0,62.0,498.0
543,JITENDER BATHINDA,NaN,09.11.23,RAPLWHL483,MAJAR SINGH,BHUNDER 151103,BATHINDA,31.0,Court Road Mata Rani Gali Janta Market Bathinda,2.0,NaN,250.0,40.0,4.0,62.0,22.0,338.0
556,JITENDER BATHINDA,NaN,14.11.23,RAPLWHL657,GURDAS SINGH,JOGEWAL 151301,BATHINDA,45.0,Court Road Mata Rani Gali Janta Market Bathinda,2.0,NaN,250.0,40.0,4.0,90.0,50.0,450.0
597,JITENDER BATHINDA,NaN,18.11.23,RAPLWHL1018,KALA SINGH,BADIALA - 151103,BATHINDA,40.0,Court Road Mata Rani Gali Janta Market Bathinda,2.0,NaN,250.0,40.0,4.0,80.0,40.0,410.0
609,JITENDER BATHINDA,NaN,23.11.23,RAPLWHL1410,GURDEEP SINGH,MAUR MANDI NEAR BUS STAND BATHINDA,BATHINDA,1.0,Court Road Mata Rani Gali Janta Market Bathinda,2.0,NaN,250.0,40.0,4.0,2.0,0.0,250.0
612,JITENDER BATHINDA,NaN,24.11.23,RAPLWHL1442,JAGGA SINGH,MISARKHANA TEH MOUR 151509,BATHINDEA,32.0,Court Road Mata Rani Gali Janta Market Bathinda,2.0,NaN,250.0,40.0,4.0,64.0,24.0,346.0
640,JITENDER BATHINDA,NaN,29.11.23,RAPLWHL1816,RAJINDER SINGH,BALIANWALI 151103,BATHINDA,30.0,Court Road Mata Rani Gali Janta Market Bathinda,2.0,NaN,250.0,40.0,4.0,60.0,20.0,330.0
725,KAMAL HOSHIARPUR,NaN,18.11.23,RAPLWHL975,RAM MOTI,HOUSE NO 368 STRRET NO 9 MOHALLA KAMLAPUR 146001,HOSHIARPUR,5.0,"Bal Mandir Senior Model Sch, new jagatpura,, n...",2.0,NaN,250.0,50.0,4.0,10.0,0.0,250.0
764,KRISHAN MOGA,NaN,28.10.23,RAPLWHK1645,HAPPY,NIHALSINGH WALA,MOGA,38.0,Firozpur road near Nestle factory galli number...,3.0,NaN,300.0,50.0,4.0,76.0,26.0,404.0
766,KRISHAN MOGA,NaN,08.11.23,RAPLWHL433,JAGJEET SINGH,BEDI NAGAR MOGA STRET NO 4 /142001,MOGA,5.0,Firozpur road near Nestle factory galli number...,2.0,NaN,300.0,50.0,4.0,10.0,0.0,300.0
775,KRISHAN MOGA,NaN,16.11.23,RAPLWHL878,RAJPAL,DAULTPURA NIWAN 142048.,MOGA,17.0,Firozpur road near Nestle factory galli number...,2.0,NaN,300.0,50.0,4.0,34.0,0.0,300.0
782,KRISHAN MOGA,NaN,22.11.23,RAPLWHL1260,RANJEET SINGH,MAHESERI SANDHUAN 142048,MOGA,18.0,Firozpur road near Nestle factory galli number...,2.0,NaN,300.0,50.0,4.0,36.0,0.0,300.0
783,KRISHAN MOGA,NaN,22.11.23,RAPLWHL1277,SONY,PATTO JAWAHAR SINGH WALA 142055,MOGA,48.0,Firozpur road near Nestle factory galli number...,2.0,NaN,300.0,50.0,4.0,96.0,46.0,484.0
785,KRISHAN MOGA,NaN,22.11.23,RAPLWHL1334,PURAN,"KAMLKE DHARAMKOT 42042,",MOGA,26.0,Firozpur road near Nestle factory galli number...,2.0,NaN,300.0,50.0,4.0,52.0,2.0,308.0
793,KRISHAN MOGA,NaN,25.11.23,RAPLWHL1565,NACCHATER SINGH,LOPON 142037,MOGA,30.0,Firozpur road near Nestle factory galli number...,2.0,NaN,300.0,50.0,4.0,60.0,10.0,340.0
798,KRISHAN MOGA,NaN,27.11.23,RAPLWHL1704,JAGJIT SINGH,BOREWALA,MOGA,31.0,Firozpur road near Nestle factory galli number...,2.0,NaN,300.0,50.0,4.0,62.0,12.0,348.0
913,LALIT UNA,NaN,16.11.23,RAPLWHL889,PARVEEN KUMAR,JHALERA 174303,UNA,6.0,Aaradhya electronics saloh 177209,2.0,NaN,250.0,30.0,4.0,12.0,0.0,250.0
918,MADAN REASI,NaN,06.11.23,RAPLWHL306,SHOBAT,SIRLA BAGHA,REASI,3.0,Madan electrical work Geeta Nager Reasi JAMMU...,2.0,NaN,300.0,20.0,4.0,6.0,0.0,300.0
952,MANPREET MALERKOTLA,NaN,11.11.23,RAPLWHL575,GULZAR KHAN,MITHEWAL 148020,MALERKOTLA,23.0,"Sant Ram Street , near Delhi gate , Malerkotla...",2.0,NaN,250.0,40.0,4.0,46.0,6.0,274.0
953,MANPREET MALERKOTLA,NaN,17.11.23,RAPLWHL945,BABU,TAKKHAR KHURAD : 148023,MALERKOTLA,7.0,"Sant Ram Street , near Delhi gate , Malerkotla...",2.0,NaN,250.0,40.0,4.0,14.0,0.0,250.0
1084,PREET SANGRUR,NaN,11.11.23,RAPLWHL584,PIYUSH,"AGGARSAIN COLONY STRRET NO 3 SAMANA 147101,",PATIALA,28.0,"Punjab National Bank And ATM, 3X7V+G7V, Dirba,...",2.0,NaN,250.0,50.0,4.0,56.0,6.0,274.0
1087,PREET SANGRUR,NaN,11.11.23,RAPLWHL599,SURESH SINGH,KALBANJARA TEH LEHRAGAGAG SANGRUR 148031,SANGRUR,20.0,"Punjab National Bank And ATM, 3X7V+G7V, Dirba,...",2.0,NaN,250.0,50.0,4.0,40.0,0.0,250.0
1189,RAJESH LUDHIANA,NaN,15.11.23,RAPLWHL780,JAGSEER SINGH,HOUSE NO 277 C RAJ GURU NAGAR LUDHIANA 141012,LUDHIANA,10.0,"Dr kuldip clinic, 4724, Shimlapuri Rd, Shimlap...",2.0,NaN,250.0,50.0,4.0,20.0,0.0,250.0
1235,RAMESH GURUGRAM,NaN,06.11.23,RAPLWHL318,DALIP,HOUSE NO 80 STRRET NO 2 COLLAGE MARUTI KUNJ,GURUGRAM,15.0,SOHNA 122103,2.0,NaN,250.0,50.0,4.0,30.0,0.0,250.0
1307,RED STAR JALANDHAR,NaN,08.11.23,RAPLWHL403,MS ELECTRONIC,PARASRAMPUR JALANDHAR 144023,JALANDHAR,6.0,"Ladowali Rd, Partap Bagh, Jalandhar, Punjab",2.0,NaN,250.0,40.0,4.0,12.0,0.0,250.0
1308,RED STAR JALANDHAR,NaN,08.11.23,RAPLWHL443,MANJU,MAHARAJA RANJIT SINGH -144009 JALANDHAR,JALANDHAR,1.0,"Ladowali Rd, Partap Bagh, Jalandhar, Punjab",3.0,NaN,250.0,40.0,4.0,2.0,0.0,250.0
1309,RED STAR JALANDHAR,NaN,08.11.23,RAPLWHL457,BHAI JAITA JI,MARKET GURU TEG BAHADUR NAGAR JALANDHAR SALON ...,JALANDHAR,5.0,"Ladowali Rd, Partap Bagh, Jalandhar, Punjab",2.0,NaN,250.0,40.0,4.0,10.0,0.0,250.0
1312,RED STAR JALANDHAR,NaN,10.11.23,RAPLWHL519,ROHIT KUMAR,GREEN VALLEY COLONY PHAGWARA 144411,KAPURTHALA,16.0,"Ladowali Rd, Partap Bagh, Jalandhar, Punjab",2.0,NaN,250.0,40.0,4.0,32.0,0.0,250.0
1325,RED STAR JALANDHAR,NaN,17.11.23,RAPLWHL958,AMIT KUMAR,HOUSER NO 1071 MODEL HOSUE TARN WALI GALI JALA...,JALANDHAR,5.0,"Ladowali Rd, Partap Bagh, Jalandhar, Punjab",2.0,NaN,250.0,40.0,4.0,10.0,0.0,250.0
1326,RED STAR JALANDHAR,NaN,18.11.23,RAPLWHL972,DAVINDER SINGH,99/18 DEAL NAGAR JALANDHAR .144003,JALANDHAR,4.0,"Ladowali Rd, Partap Bagh, Jalandhar, Punjab",2.0,NaN,250.0,40.0,4.0,8.0,0.0,250.0
1331,RED STAR JALANDHAR,NaN,21.11.23,RAPLWHL1202,GURJANT SINGH,10 MMAN SINGH NAHAR JALNDHAR 144001,JALANDHAR,4.0,"Ladowali Rd, Partap Bagh, Jalandhar, Punjab",2.0,NaN,250.0,40.0,4.0,8.0,0.0,250.0
1340,RED STAR JALANDHAR,NaN,08.11.23,RAPLWHL450,JAGTAR SINGH,"MANAK LOHIAN KHAS 144629, JAQLANDHAR",JALANDHAR,45.0,"Ladowali Rd, Partap Bagh, Jalandhar, Punjab",2.0,NaN,250.0,40.0,4.0,90.0,50.0,450.0
1398,SHIV PRASAD DEHRADUN,NaN,07.11.23,RAPLWHL351,SURESH,HOUSE NO 38/6 VASY ESTATE CANAL ROAD LAKHAN,DEHRADUN,8.0,NEHRU COLONY,2.0,NaN,250.0,50.0,4.0,16.0,0.0,250.0
1490,SUBASH MANSA,NaN,21.11.23,RAPLWHL1241,BABLU,WARD NO DODRA TEH BHUDLADA 151502,MANSA,26.0,near bus stand raman cinema road mansa 151505,2.0,NaN,250.0,40.0,4.0,52.0,12.0,298.0
1561,VIJAY KATHUA,NaN,20.11.23,RAPLWHL1133,GANGA SPA,SHOP NO SAINIK COLONY JAMMU 180011 2 PCS,JAMMU,10.0,JAMMU,1.0,NaN,350.0,20.0,4.0,20.0,0.0,350.0
1609,VINOD DELHI,NaN,17.11.23,RAPLWHL894,ASHRIF,D 571 1ND FLOOR JJ COLONY WAZIRPUR NORTH WEST ...,DELHI,18.0,B-54 SHAKTI VIHAR MOHAN GARDEN UTTAM NAGAR WES...,3.0,NaN,300.0,40.0,4.0,36.0,0.0,300.0

In [ ]:
 df['REMARK'] = df['REMARK'].str.extract(r'(\d+)').astype(float)[0]

In [ ]:
df['']

Empty DataFrame
Columns: [Service Center Name_x, COMPLAINT CLOSE DATE, COMPLAINT SEND & REC. DATE, COMPLAINT NO, NAME, ADDRESS, DISTRICT, Distances, TREVELLING FROM, REMARK, LOCATION/2 PCS/2 VISIT, PER COMPLAINT, KILOMETER UPDOWN, PER KM, up_down_dist, difference, total_amount]
Index: []

In [ ]:
df.shape

(1639, 17)